Repository COS301-SE-2024/MovieHub, pull requests merged in 2024-09, with the labels that each got.

#298 Origin/dev/UI fixes and changes
  assets/black white clean movie logo (2).png
  assets/logo.png
  assets/logo2.png
  frontend/src/Components/BottomHeader.js
  frontend/src/Components/HomeHeader.js
  frontend/src/Components/HubTabView.js
  frontend/src/Screens/CreatePost.js
  frontend/src/Screens/CreateRoom.js
  frontend/src/Screens/ExplorePage.js
  frontend/src/Screens/HubScreen.js
  frontend/src/Screens/LoginPage.js
  frontend/src/Screens/SignupPage.js
Labels: frontend

#319 HomePage Recommender To Dev
  backend/src/Recommender/recommender.service.js
  backend/src/scripts/indexMovies.js
  backend/src/scripts/setUpElastic.js
  backend/src/utils/vectorizeMovies.js
  frontend/src/Screens/ExplorePage.js
  frontend/src/Screens/MovieDescriptionPage.js
  frontend/src/Services/RecApiService.js
Labels: integration

#394 Update README.md
  README.md
Labels: documentation
